services:
  app:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /usr/app
    env_file:
      - .env

  # app-builder:
  #   build:
  #     context: .
  #     target: builder

  # app-prod:
  #   build:
  #     context: .
  #     target: prod
